app/models.py
#-*- coding:utf-8 -*-

from . import db

class JobInfo(db.Model):
    __tablename__ = 'jobs'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))                    # 任务名称
    job_id = db.Column(db.String(128), unique=True)     # 关联celery的jobid
    job_type = db.Column(db.String(50))                 # 任务类型
    user_id = db.Column(db.Integer)                     # 操作用户
    export_file = db.Column(db.String(255))             # 导入的文件名称，或导出的文件名称
    result = db.Column(db.String(32))                   # 任务结果
    version = db.Column(db.String(16), default='1.0')   # 任务版本号
    plugin = db.Column(db.String(64))                   # 源数据类型
    plugin_name = db.Column(db.String(128))             # 源数据名称
    host = db.Column(db.String(32))                     # 数据库主机
    port = db.Column(db.Integer)                        # 数据库端口
    db_name = db.Column(db.String(128))                 # 数据库名称
    table_name = db.Column(db.String(128))              # 数据库表名
    rule = db.Column(db.Text)                           # 提取规则
    job_dones = db.Column(db.Integer, default=0)        # 任务运行次数
    is_run = db.Column(db.Boolean, default=False)       # 任务是否在运行

    def to_json(self):
        json_config = {
            "id":self.id,
            "type":self.job_type,
            "version":self.version,
            "job_celery_id":self.job_id,
            "job_name":self.name,
            "plugin":self.plugin,
            "plugin_name":self.plugin_name,
            "host":self.host,
            "port":self.port,
            "db":self.db_name,
            "table_name":self.table_name,
            "rule":self.rule,
            "job_dones":self.job_dones,
        }
        return json_config

app/main/forms.py
#-*- coding:utf-8 -*-

from flask_wtf import Form
from wtforms import (IntegerField, StringField, TextAreaField, BooleanField, SelectField,
    SubmitField)
from wtforms.validators import Required


class ConfigForm(Form):
    job_name = StringField(u'任务名称', validators=[Required()])
    job_type = SelectField(u'任务类型', coerce=int)
    db_source_type = SelectField(u'源数据类型', coerce=int)
    db_source_name = StringField(u'源数据名称', validators=[Required()])
    db_host = StringField(u'主机地址', validators=[Required()])
    db_port = IntegerField(u'端口', validators=[Required()])
    db_name = StringField(u'数据库名称', validators=[Required()])
    #user_name = StringField(u'用户名', validators=[Required()])
    #user_pwd = StringField(u'密码', validators=[Required()])
    table_name = StringField(u'表名', validators=[Required()])
    rule = TextAreaField(u'提取规则')
    export_filename = StringField(u'导出文件名', validators=[Required()])
    submit = SubmitField(u'提交')

    def __init__(self, *args, **kwargs):
        super(ConfigForm, self).__init__(*args, **kwargs)
        self.job_dict = {'1':u'即时输出日志任务',
                        '10':'MongoDB',
                        '20':'MySql',
                        '30':'SQLServer'}
        self.job_type.choices = [(1,u'即时输出日志任务')]
        self.db_source_type.choices = [(10,'MongoDB'),(20,'MySql'),(30,'SQLServer')]

    def get_name(self, value):
        return self.job_dict[str(value)]

app/__init__.py
#-*- coding:utf-8 -*-
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from celery import Celery
from config import config, Config


bootstrap = Bootstrap()
db = SQLAlchemy()


celery = Celery(__name__, broker=Config.CELERY_BROKER_URL)


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)

    celery.conf.update(app.config)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from . import main
from flask import render_template, request, url_for, redirect, flash
from flask import jsonify
from ..tasks.job import mysqlTomongoDB
from .forms import ConfigForm
from ..job.jobconfig import JobConfig
from ..models import JobInfo
from .. import db
import json

@main.route('/', methods=['GET', 'POST'])
def index():
    form = ConfigForm()
    if form.validate_on_submit():
        job = JobInfo(name=form.job_name.data,
                    job_type=form.get_name(form.job_type.data),
                    plugin=form.get_name(form.db_source_type.data),
                    plugin_name=form.db_source_name.data,
                    host=form.db_host.data,
                    port=form.db_port.data,
                    db_name=form.db_name.data,
                    table_name=form.table_name.data,
                    rule=form.rule.data,
                    export_file=form.export_filename.data
                    )
        db.session.add(job)
        db.session.commit()
        flash('You have successfully created a task')
        return redirect(url_for('.jobs'))
    return render_template('index.html', form=form)

@main.route('/jobs')
def jobs():
    jobs = JobInfo.query.all()
    return render_template('jobs.html', jobs=jobs)


@main.route('/job/<int:id>')
def job(id):
    job = JobInfo.query.get_or_404(id)
    return render_template('job_detail.html', job=job)

@main.route('/run', methods=['POST'])
def run():
    data = json.loads(request.form.get('data'))
    id = data.get('id', 0)
    job = JobInfo.query.get_or_404(id)
    if job is not None:
        job.job_dones += 1
        db.session.add(job)
        db.session.commit()
    try:
        task = mysqlTomongoDB.delay(id)
        job.job_id = task.id
        job.is_run = True
        db.session.add(job)
        db.session.commit()
    except Exception, e:
        print '%s'  % e
        raise e

    return jsonify({}), 202, {'Location': url_for('main.taskstatus',task_id=task.id)}


@main.route('/job/status/<task_id>')
def taskstatus(task_id):
    task = mysqlTomongoDB.AsyncResult(task_id)
    if task.state == 'PENDING':
        response = {
            'state':task.state,
            'current':0,
            'total':1,
            'status':'pending.....',
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'current': task.info.get('current', 0),
            'total': task.info.get('total', 1),
            'status': task.info.get('status', '')
        }
        if 'result' in task.info:
            response['result'] = task.info['result']
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'current': 1,
            'total': 1,
            'status': task.info,  # this is the exception raised
        }
    return jsonify(response)

@main.route('/delete', methods=['POST'])
def del_job():
    id = request.values.get('id', 0)
    job = JobInfo.query.get_or_404(id)
    try:
        db.session.delete(job)
        db.session.commit()
        return 'ok'
    except Exception, e:
        return 'fail'

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}任务调度演示{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.jobs') }}">Jobs</a></li>
            </ul>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
  <div class="row clearfix">
    <div class="col-md-6 column">
    <h3>任务填写配置</h3>
    {{ wtf.quick_form(form) }}
    </div>
    <div class="col-md-6 column">
    </div>
  </div>
</div>

{% endblock %}

app/templates/job_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-8 column">
           <h3>作业详情</h3>
           <table class="table table-bordered">
               <thead>
                   <tr>
                       <th>作业参数</th>
                       <th>参数值</th>
                   </tr>
               </thead>
               <tbody>
                   <tr>
                       <td>编号</td>
                       <td id="job_id">{{ job.id }}</td>
                   </tr>
                   <tr>
                       <td>任务名称</td>
                       <td>{{ job.name }}</td>
                   </tr>
                   <tr>
                       <td>Task ID</td>
                       <td>{{ job.job_id}}</td>
                   </tr>
                   <tr>
                       <td>任务类型</td>
                       <td>{{ job.job_type}}</td>
                   </tr>
                   <tr>
                       <td>源数据类型</td>
                       <td>{{ job.plugin}}</td>
                   </tr>
                   <tr>
                       <td>源数据名称</td>
                       <td>{{ job.plugin_name}}</td>
                   </tr>
                   <tr>
                       <td>主机</td>
                       <td>{{ job.host}}</td>
                   </tr>
                   <tr>
                       <td>端口</td>
                       <td>{{ job.port }}</td>
                   </tr>
                   <tr>
                       <td>数据库名称</td>
                       <td>{{ job.db_name }}</td>
                   </tr>
                   <tr>
                       <td>数据库表名</td>
                       <td>{{ job.table_name }}</td>
                   </tr>
                   <tr>
                       <td>提取规则</td>
                       <td>{{ job.rule }}</td>
                   </tr>
                   <tr>
                       <td>导入(导出)文件名</td>
                       <td>{{ job.export_file }}</td>
                   </tr>
                   <tr>
                       <td>运行状态</td>
                       <td>{{ job.is_run }}</td>
                   </tr>
                   <tr>
                       <td>任务结果</td>
                       <td>{{ job.result }}</td>
                   </tr>
                   <tr>
                       <td>运行次数</td>
                       <td>{{ job.job_dones }}</td>
                   </tr>
               </tbody>
           </table>
        </div>
        <div class="col-md-4 column">
            <h3>任务操作</h3>
            <hr>
            <div class="row clearfix">
                <div class="col-md-6 column">
                     <button id="1" type="button" class="btn btn-info btn-info"
                                        onclick="run_job({{ job.id }});">启动</button>
                </div>
                <div class="col-md-6 column">
                     <button id="1" type="button" class="btn btn-info btn-warning"
                                        onclick="pause_job({{ job.id }});">暂停</button>
                </div>
            </div>
            <hr>
            <h4>任务运行状态</h4>
            <br>
            <div class="progress">
                <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuenow="60"
                    aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                    <span id="progress-persent">0%</span>
                </div>

            </div>
            <p id="status">等待运行......</p>
            <hr>
            <h4>任务运行结果</h4>
            <br>
            <h5 id="result">未运行.....</h5>
        </div>
    </div>
</div>
<script type="text/javascript">
    /*function myfun()
　　{
        var id = $("#job_id").text();
 　　   run_job(parseInt(id));
　　}*/
　　/*用window.onload调用myfun()*/
　　/*window.onload = myfun;*/

    function run_job(jobid) {
        var data = {data: JSON.stringify({"id":jobid})};
        $.ajax({
                type: 'POST',
                url: "{{url_for('main.run')}}",
                data: data,
                success: function(data, status, request) {
                    status_url = request.getResponseHeader('Location');
                    update_progress(status_url);
                },
                error: function() {
                    alert('Unexpected error');
                }
            });
        /*$("#job"+jobid).addClass("disabled");*/
    }
    function update_progress(status_url) {
      // send GET request to status URL
      $.getJSON(status_url, function(data) {
          // update UI
          percent = parseInt(data['current']);
          $('#progress-bar').css('width', percent+'%')
          $('#progress-persent').text(percent + '%');
          $('#status').text(data['status']);
          if (data['state'] != 'PENDING' && data['state'] != 'PROGRESS') {
              if ('result' in data) {
                  // show result
                  $('#result').text('Result: ' + data['result']);
              }
              else {
                  // something unexpected happened
                  $('#result').text('Result: ' + data['state']);
              }
          }
          else {
              // rerun in 2 seconds
              setTimeout(function() {
                  update_progress(status_url);
              }, 2000);
          }
      });
    }
    function pause_job(jobid) {
        alert("pause job success!");
    }
</script>
{% endblock %}

app/templates/jobs.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
        <h2>任务列表</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>编号</th>
                        <th>任务名称</th>
                        <th>ID</th>
                        <th>任务类型</th>
                        <th>源数据类型</th>
                        <th>源数据名称</th>
                        <th>任务结果</th>
                        <th>运行次数</th>
                        <th>操作</th>
                        <th>更多</th>
                    </tr>
                </thead>
                <tbody>
                {% for job in jobs %}
                    <tr id="job_{{job.id}}">
                        <td>{{ job.id }}</td>
                        <td>{{ job.name }}</td>
                        <td>{{ job.job_id}}</td>
                        <td>{{ job.job_type }}</td>
                        <td>{{ job.plugin }}</td>
                        <td>{{ job.plugin_name }}</td>
                        <td>{{ job.result }}</td>
                        <td>{{ job.job_dones }}</td>
                        <td><button id="job{{job.id}}" type="button" class="btn-xs btn-info btn-danger"
                                      data-toggle="modal" data-target="#myModal{{job.id}}">删除</button>
                        </td>
                        <td><a href="{{ url_for('main.job', id=job.id )}}">详细</a></td>
                    </tr>
                    <!-- delete job modal -->
                    <div class="modal fade" id="myModal{{job.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="myModalLabel">警告</h4>
                                </div>
                                <div class="modal-body">是否确认删除该任务？</div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                    <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="del_job({{job.id}});">删除</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal -->
                    </div>
                    <!-- end delete job modal -->
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
  function del_job(jobid) {
    $.post("{{url_for('main.del_job')}}", {'id':jobid}, function(resp){
      if(resp == 'ok'){
        $('#job_' + jobid).remove();
      }else{
        alert("delete fail!");
      }
    });
  }
</script>
{% endblock %}